// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfltcqtvqoquqfixkgvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbHRjcXR2cW9xdXFmaXhrZ3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjY4MjIsImV4cCI6MjA2OTkwMjgyMn0.PEgeFunBzluyZ194SPaIHS_a09Z3EF-bL2M5NQEaBfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});